remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins

title : "SAE 2.03 Equipe 14"
description : "Compte rendu de notre activit√© lors de cette SAE"
